### ISSUE TITLE
pretty_color vs. generate_color

### ISSUE THREAD

**Issue by kentavv** [mwisslead/prettycolors#1]
The readme.md uses pretty_color but the code has generate_color. Is generate_color correct or is pretty_color missing? I'm seeing colors (lots of pale blues and greens) different from the first readme.md example after modifying the example to use
`img = np.reshape([generate_color(c) for c in range(colors)], (factor, colors//factor, 3))`
although the following seems to match the second example colors.
`img = np.reshape(generate_colors(colors), (factor, colors//factor, 3))`
Otherwise, all is _pretty_(colors) cool :)

**Comment by mwisslead** [comment]
Turns out the hsv_to_rgb function takes a hue between 0 and 1 instead of 0 and 360
